### ISSUE TITLE
Could you reproducte the vocal SDR performance (above 10.04 dB) ?

### ISSUE THREAD

**Issue by agangzz** [amanteur/BandSplitRNN-Pytorch#1]
Thanks your great implementation.  Could you reproduce the vocal SDR performance (uSDR=10.04 dB) ? Could you provide your pretrain model ? Thanks

**Comment by amanteur** [comment]
Hi, @agangzz! 
Thank you for the first issue! 

I've just updated the repo, and added the link to the vocal checkpoint and its uSDR/cSDR. Sadly, the performance is quite poor (around 5.5dB). At this point, I think, it is either some very silly error somewhere in the model architecture, or the architecture by itself is not enough to make it to >10dB.

**Comment by ycyang133** [comment]
> Hi, @agangzz! Thank you for the first issue!
> 
> I've just updated the repo, and added the link to the vocal checkpoint and its uSDR/cSDR. Sadly, the performance is quite poor (around 5.5dB). At this point, I think, it is either some very silly error somewhere in the model architecture, or the architecture by itself is not enough to make it to >10dB.

Hi, @amanteur 
Thank you for your implementation. I am recently working on this work and I want to know if you find some crucial issues affecting the performance on training the model.

Thank you very much.
