### ISSUE TITLE
Error in inference.py and separator.py

### ISSUE THREAD

**Issue by ripnonfegames** [amanteur/BandSplitRNN-Pytorch#13]
python inference.py -i back.mp3 -o vocalsonly -t vocals -c .\saved_models\vocals\vocals_upd.pt gives me a huge error.

`Traceback (most recent call last):
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\src\inference.py", line 112, in <module>
    main(args)
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\src\inference.py", line 65, in main
    program = InferenceProgram(**args)
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\src\inference.py", line 46, in __init__
    self.sep = Separator(self.cfg, self.ckpt_path)
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\src\separator.py", line 26, in __init__
    self.model = self.initialize_modules()
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\src\separator.py", line 62, in initialize_modules
    _ = model.load_state_dict(state_dict, strict=True)
  File "C:\Users\Nicolas Hinds\Downloads\Compressed\BandSplitRNN-Pytorch-main\venv\lib\site-packages\torch\nn\modules\module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BandSplitRNN:
        Missing key(s) in state_dict: "bandsplit.layernorms.0.weight", "bandsplit.layernorms.0.bias",`
etc

renaming vocals_upd to vocals.pt and doing python inference.py -i back.mp3 -o vocalsonly -t vocals has the same effect.

**Comment by a0950088** [comment]
I have the same problem and found that this is the env you use to train the model and test load the model are inconsistent. 
I changed `model.load_state_dict(state_dict, strict=True)` to `model.load_state_dict(state_dict, strict=False)` in separator.py line 62, and it works fine.

**Comment by epcm** [comment]
I encountered the same question. It didn't work to just set strict=False, the weights were not actually loaded in this way. The problem is that names of parameters are different between the pre-trained model and the model defined in this program. Just revise names of parameters in the program before you load weights from pre-trained model, it works fine.

```python
  state_dict = torch.load(ckpt_path, map_location=self.device)

  # create new state dict with names consistent with pre-trained model
  new_state_dict = OrderedDict()
  prefix_to_remove = 'model.'  
  for key, value in state_dict.items():
    if key == "featurizer.window" or key == "inverse_featurizer.window":
        continue
    if key.startswith(prefix_to_remove):
        new_key = key[len(prefix_to_remove):]  
        new_state_dict[new_key] = value
    else:
        new_state_dict[key] = value
  state_dict = new_state_dict
  
  _ = self.sep.model[1].load_state_dict(state_dict, strict=True)
```

**Comment by amanteur** [comment]
Hey guys!

Sorry for inconvenience. 
I renamed the keys in state dict and updated the link, so now it should work.

**Comment by epcm** [comment]
Thanks a lot for your great implementation! BTW, are there better results on vocals or other sources now?

**Comment by amanteur** [comment]
@epcm Sadly, had no time to fully revisit this project:(
