### ISSUE TITLE
Training with not MUSDB18 Datasets

### ISSUE THREAD

**Issue by Super-YH** [amanteur/BandSplitRNN-Pytorch#2]
Hello.

I want to train this model with not MUSDB18 dataset.

But In prepare_dataset.py, It can only be used in Musdb18 Dataset.

So I want to know, how to train without Musdb18 dataset.

**Comment by amanteur** [comment]
Hi, @Super-YH! 

As a fast solution, you can compose your dataset's file structure in style of MUSDB18 dataset. 

Something like this:
```
your-dataset/
├── train
│   ├── filename1
│       ├── bass.wav
│       ├── drums.wav
│       ├── other.wav
│       └── vocals.wav
│   └── ...
│   └── filenameN
│       ├── bass.wav
│       ├── drums.wav
│       ├── other.wav
│       └── vocals.wav
└── test
│   └── {same as train}
```

Also, as I used `musdb` package, there is a predefined list of validation tracks in `validation_tracks` in `musdb/configs/mus.yaml`. You can redefine this config and put your own validation tracks from `train` directory.

Hope it helps!
