### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by Mosferator** [amanteur/BandSplitRNN-Pytorch#3]
Hi,
Congrats for all of these, excellent work!
Maybe you can find some spare time to update everything to Python 3.11
It's not nice to have 3.10 and 3.11 on the same machine.

**Comment by amanteur** [comment]
Hi @Mosferator,

Thank you!

One solution would be to create a virtual environment with `Python 3.10` using either `conda` or `venv`, and then clone the repository. This way, you can keep your `Python 3.11` installation separate from the virtual environment, avoiding conflicts.

I hope this helps! Let me know if you have any other questions.

**Comment by Mosferator** [comment]
Hi @amanteur 

I think the right solution would be a bit of refactor for 3.11 and the requirements.txt changed in this way:
torch>=1.8.1
torchaudio>=0.8
pytorch-lightning>=1.9
musdb
numpy
hydra-core>=1.1
omegaconf>=2.3
tensorboard>=2.12
tqdm
museval
