### ISSUE TITLE
Pre trained model available?

### ISSUE THREAD

**Issue by TheMakerOfWorlds** [amanteur/BandSplitRNN-Pytorch#7]
Hey thank you for your amazing work! I was wondering if there is a pretrained model available for this, and if there ever will be, thank you!  

also, how does processing time compare to [Demus](https://github.com/facebookresearch/demucs) all things being equal?

**Comment by amanteur** [comment]
Hey!

There is one [pretrained](https://drive.google.com/file/d/1d4AV3sH7mhVed8L9ch5otXB0HzjCPnw0/view?usp=sharing) model for extracting vocals, and that's it. 

Regarding processing time, it is slower than Demucs mostly due to heavy RNN module within the model.

**Comment by lixucuhk** [comment]
Excuse me, the link is not valid now. Could you please provide a new one? Thank you!
