### ISSUE TITLE
Training Issue

### ISSUE THREAD

**Issue by will46616** [amanteur/BandSplitRNN-Pytorch#8]
Hi, I'm having some problems with my training. I didn't change the contents of the config, but I get the following error : 
TypeError: on_before_optimizer_step() missing 1 required positional argument: 'optimizer_idx'

May I ask what is the problem that causes the error in trainer.fit?

**Comment by leyangxing** [comment]
> 

Hello, I have also encountered this problem. Have you resolved it?

**Comment by will46616** [comment]
I just removed the optimizer_idx of the on_before_optimizer_step function in pl_model.py.

**Comment by leyangxing** [comment]
> I just removed the optimizer_idx of the on_before_optimizer_step function in pl_model.py.

I see.Thank you very much for your timely answer！！！

**Comment by amanteur** [comment]
Hey!

Thank you for resolving an issue! 
I've just updated the code and removed ```optimizer_idx``` from ```on_before_optimizer_step```.
