### ISSUE TITLE
Bug in MaskEstimationModule?

### ISSUE THREAD

**Issue by unemployed-denizen** [amanteur/BandSplitRNN-Pytorch#9]
Hello, in the class MaskEstimationModule, should we add an extra line of code to permute the tensor before reshaping that? Otherwise the meaning of the dimensions may not match?

![image](https://github.com/amanteur/BandSplitRNN-Pytorch/assets/63128680/c720a8ec-4ab4-4888-b82a-2387e413d4a6)

**Comment by amanteur** [comment]
Hey!

Thank you for bringing this to my attention! You're right, it is indeed a bug.

If you're interested in contributing and helping to fix this issue, your pull request is welcome!
